project:
  type: website

execute:
  freeze: auto

website:
  title: "Data journalism training"
  navbar:
    background: "#222222"
    left:
      - text: Home
        href: index.qmd
      - text: Lessons
        menu:
          - text: Scraping from cards and dashboards
            href: lessons/scraping-cards/index.qmd

format:
  html:
    theme: [default, style.scss]
    linkcolor: "#36a7e9"
    css: styles.css
    toc: true
