project:
  type: website

execute:
  freeze: auto

website:
  title: "Training"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scraping-cards
        text: Scraping cards

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
